title: Ivox
baseURL: /
params:
  description: Ivox's website - Content Hub
  color_scheme: dark
  accent_color: blue
  header:
    type: header
    title: Ivox
    has_nav: true
    nav_links:
      - type: action
        label: Home
        url: /
        style: link
      - type: action
        label: Portfolio
        url: /portfolio/
        style: link
      - type: action
        label: Blog
        url: /blog/
        style: link
      - type: action
        label: Style Guide
        url: /style-guide/
        style: link
      - type: action
        label: About
        url: /about/
        style: link
      - type: action
        label: Contact
        url: /contact/
        style: link
    logo_img: /images/General logo.png
  footer:
    type: footer
    content: '&copy; Stackbit-Exto. All rights reserved.'
    links:
      - type: action
        label: Made with Stackbit.
        url: 'https://www.stackbit.com'
        style: link
        new_window: true
    has_social: true
    social_links:
      - type: action
        label: Twitter
        url: 'https://twitter.com/'
        style: icon
        icon_class: fa-twitter
        new_window: true
      - type: action
        label: Instagram
        url: 'https://www.instagram.com/'
        style: icon
        icon_class: fa-instagram
        new_window: true
      - type: action
        label: Dribbble
        url: 'https://dribbble.com/'
        style: icon
        icon_class: fa-dribbble
        new_window: true
      - type: action
        label: LinkedIn
        url: 'https://www.linkedin.com/'
        style: icon
        icon_class: fa-linkedin
        new_window: true
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
